force-app/main/default/objects/phsUGPerformance__c/phsUGPerformance__c.object-meta.xml
<CustomObject>
    <label>phsUGPerformance</label>
    <nameField>
        <label>phsUGPerformance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsUGPerformance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsUGPerformance__c/fields/ChallengesFaced__c.field-meta.xml
<CustomField>
    <fullName>ChallengesFaced__c</fullName>
    <label>ChallengesFaced</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUGPerformance__c/fields/FocusQuality__c.field-meta.xml
<CustomField>
    <fullName>FocusQuality__c</fullName>
    <label>FocusQuality</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUGPerformance__c/fields/StressLevel__c.field-meta.xml
<CustomField>
    <fullName>StressLevel__c</fullName>
    <label>StressLevel</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUGPerformance__c/fields/SuccessStories__c.field-meta.xml
<CustomField>
    <fullName>SuccessStories__c</fullName>
    <label>SuccessStories</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUGPerformance__c/fields/TimeInFlowState__c.field-meta.xml
<CustomField>
    <fullName>TimeInFlowState__c</fullName>
    <label>TimeInFlowState</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUGPerformance__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to Contact Object</description>
    <label>UserId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>phsUGPerformance</relationshipLabel>
    <relationshipName>phsUGPerformance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/phsMyTeamsControllerTest.cls
@isTest
public class phsMyTeamsControllerTest {
       
    private static Contact createContact() {
        Contact c = new Contact(
            LastName = 'Test Contact',
            Email = 'test' + System.currentTimeMillis() + '@example.com',
            Title='Test'
        );
        insert c;
        return c;
    }
    
    @IsTest static void testgetMyTeamList() 
    {
        Contact c=phsMyTeamsControllerTest.createContact();
        Contact c2=phsMyTeamsControllerTest.createContact();
        c2.ReportsToId=c.Id;
        update c2;
        phsUGPerformance__c obj=new phsUGPerformance__c(ChallengesFaced__c='Time',FocusQuality__c=1.0,Name='Test',StressLevel__c=1.0,
                                                        SuccessStories__c='Story',TimeInFlowState__c=1.0,UserId__c=c.Id);
        insert obj;    
        Test.startTest();
        String results=  phsMyTeamsController.getMyTeamList();
        Test.stopTest();
        System.assert(results.contains('Test'));
        System.debug('Test : '+ results);
        
    }
}