force-app/main/default/objects/phsUGPerformance__c/phsUGPerformance__c.object-meta.xml
<CustomObject>
    <label>phsUGPerformance</label>
    <nameField>
        <label>phsUGPerformance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsUGPerformance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsUGPerformance__c/fields/FocusQuality__c.field-meta.xml
<CustomField>
    <fullName>FocusQuality__c</fullName>
    <label>FocusQuality</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUGPerformance__c/fields/StressLevel__c.field-meta.xml
<CustomField>
    <fullName>StressLevel__c</fullName>
    <label>StressLevel</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUGPerformance__c/fields/TimeInFlowState__c.field-meta.xml
<CustomField>
    <fullName>TimeInFlowState__c</fullName>
    <label>TimeInFlowState</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUGPerformance__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to Contact Object</description>
    <label>UserId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>phsUGPerformance</relationshipLabel>
    <relationshipName>phsUGPerformance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/phsMyTeamsController.cls
public without sharing  class phsMyTeamsController {
    
    
    @AuraEnabled() 
    public static string getMyTeamList() {
        try
        {
            phsUtilityController utility=new phsUtilityController();
            String userId=utility.getContactId();
            
            List<Contact> clist=new List<Contact>();
            List<myTeam> myteamlist=new List<myTeam>();
            clist=[SELECT Id , Title , Name FROM Contact where ReportsToId  =: userId ];
            
            for(Contact c : clist)
            {
                myTeam mt=new myTeam();
                mt.Id=c.Id;
                mt.Title=c.Title;
                mt.Name=c.Name;
                List<phsUGPerformance__c> uglist=new List<phsUGPerformance__c>();
                
                uglist=[Select Id, TimeInFlowState__c, StressLevel__c, FocusQuality__c  from phsUGPerformance__c where  UserId__c =: mt.Id];
                for(phsUGPerformance__c u :uglist )
                {
                    
                    mt.StressLevel=u.StressLevel__c;
                    mt.FocusQuality=u.FocusQuality__c;
                    mt.TimeInFlowState=u.TimeInFlowState__c;
                }
                myteamlist.add(mt);
            }
            String jsonResponse = JSON.serialize(myteamlist);
            return jsonResponse;
        }
        catch(Exception e)
        {
            System.debug('The following exception has occurred: ' + e.getMessage()); 
            String jsonResponse = JSON.serialize(e.getMessage());
            return jsonResponse;
        }
    }
    
    public class myTeam
    {
        public String Id;
        public STring Title;
        public String Name;
        public double StressLevel=0;
        public double FocusQuality=0;
        public double TimeInFlowState=0;
        
    }
    
}