force-app/main/default/objects/Contact/fields/App_Role__c.field-meta.xml
<CustomField>
    <fullName>App_Role__c</fullName>
    <description>This field identifies role hierarchy for F2F app</description>
    <inlineHelpText>Role hierarchy for Team</inlineHelpText>
    <label>App Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual User</fullName>
            </value>
            <value>
                <fullName>System Admin</fullName>
            </value>
            <value>
                <fullName>Organizational Admin</fullName>
            </value>
            <value>
                <fullName>Team Manager</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsUGPerformance__c/phsUGPerformance__c.object-meta.xml
<CustomObject>
    <label>phsUGPerformance</label>
    <nameField>
        <label>phsUGPerformance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsUGPerformance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsUGPerformance__c/fields/ChallengesFaced__c.field-meta.xml
<CustomField>
    <fullName>ChallengesFaced__c</fullName>
    <label>ChallengesFaced</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUGPerformance__c/fields/FocusQuality__c.field-meta.xml
<CustomField>
    <fullName>FocusQuality__c</fullName>
    <label>FocusQuality</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUGPerformance__c/fields/StressLevel__c.field-meta.xml
<CustomField>
    <fullName>StressLevel__c</fullName>
    <label>StressLevel</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUGPerformance__c/fields/SuccessStories__c.field-meta.xml
<CustomField>
    <fullName>SuccessStories__c</fullName>
    <label>SuccessStories</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUGPerformance__c/fields/TimeInFlowState__c.field-meta.xml
<CustomField>
    <fullName>TimeInFlowState__c</fullName>
    <label>TimeInFlowState</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUGPerformance__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to Contact Object</description>
    <label>UserId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>phsUGPerformance</relationshipLabel>
    <relationshipName>phsUGPerformance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/phsUserPerformanceController.cls
public class phsUserPerformanceController {
 @AuraEnabled(cacheable=true) 
    public static String getUserPerformanceDetails() {
        
        String userId=new phsUtilityController().getContactId();
        List<phsUGPerformance__c> userperformance = new List<phsUGPerformance__c>(); 
       // userId=new phsUtilityController ().decrypt(userId);
        uGPerformance obj=new uGPerformance();
      //  obj.successStories=userId;
        try
        {
        userperformance = [SELECT Id , StressLevel__c , SuccessStories__c  ,TimeInFlowState__c, FocusQuality__c, ChallengesFaced__c ,UserId__c
                            FROM phsUGPerformance__c where UserId__c =: userId ];
         if(userperformance.size() > 0)
          {
              obj.stressLevel=userperformance[0].StressLevel__c; 
              obj.timeInFlowState=userperformance[0].TimeInFlowState__c;
              obj.focusQuality=userperformance[0].FocusQuality__c;
              obj.successStories=userperformance[0].SuccessStories__c;
              obj.challengesFaced=userperformance[0].ChallengesFaced__c;
              obj.keyId=userperformance[0].Id;
          }
           
            
            List<Contact> c=[Select App_Role__c from Contact where Id=: userId];
            if(c.size()>0)
            {
                obj.appRole=c[0].App_Role__c;
            }
            
        }
        catch(Exception e)
        {
            System.debug('The following exception has occurred: ' + e.getMessage());    
        }
        String jsonResponse = JSON.serialize(obj);
        return jsonResponse;
    }
    
    @AuraEnabled() 
    public static String getMyUserPerformanceDetails(String userId) {
        
      //  String userId=new phsUtilityController().getContactId();
        List<phsUGPerformance__c> userperformance = new List<phsUGPerformance__c>(); 
       // userId=new phsUtilityController ().decrypt(userId);
        uGPerformance obj=new uGPerformance();
      //  obj.successStories=userId;
        try
        {
        userperformance = [SELECT Id , StressLevel__c , SuccessStories__c  ,TimeInFlowState__c, FocusQuality__c, ChallengesFaced__c ,UserId__c
                            FROM phsUGPerformance__c where UserId__c =: userId ];
         if(userperformance.size() > 0)
          {
              obj.stressLevel=userperformance[0].StressLevel__c; 
              obj.timeInFlowState=userperformance[0].TimeInFlowState__c;
              obj.focusQuality=userperformance[0].FocusQuality__c;
              obj.successStories=userperformance[0].SuccessStories__c;
              obj.challengesFaced=userperformance[0].ChallengesFaced__c;
              obj.keyId=userperformance[0].Id;
          }
           
            
            List<Contact> c=[Select App_Role__c from Contact where Id=: userId];
            if(c.size()>0)
            {
                obj.appRole=c[0].App_Role__c;
            }
            
        }
        catch(Exception e)
        {
            System.debug('The following exception has occurred: ' + e.getMessage());    
        }
        String jsonResponse = JSON.serialize(obj);
        return jsonResponse;
    }
    
    
    class uGPerformance
    {
        public Decimal stressLevel;
        public Decimal timeInFlowState;
        public Decimal focusQuality;
        public String successStories;
        public String challengesFaced;
        public String keyId;
        public String appRole;
        
    }
    
       @AuraEnabled() 
    public static String updatePerformance(String upId, double stressLevel,double focusQuality, 
                                 double timeInFlowState,String challengesFaced, String successStories ) {
                                 
                                    try
                                    {
                                     

                                        List<phsUGPerformance__c> a = [SELECT Id, StressLevel__c , SuccessStories__c  ,TimeInFlowState__c, FocusQuality__c, ChallengesFaced__c from phsUGPerformance__c WHERE Id  =: upId Limit 1];
    								
                                        for(phsUGPerformance__c obj : a)
                                        {
                                        obj.StressLevel__c = stressLevel;
                                        obj.TimeInFlowState__c = timeInFlowState;
                                        obj.FocusQuality__c = focusQuality;
                                        obj.ChallengesFaced__c = challengesFaced;
                                        obj.SuccessStories__c = successStories;
                                        }
                                       if(a.size()>0 && a !=null){
           									update a;

  										}
    									
                                            
                                             String jsonResponse = JSON.serialize('Updated');
       										 return jsonResponse;
                                    }
                                     catch(Exception e)
                                     {
                                         System.debug('The following exception has occurred: ' + e.getMessage()); 
                                              String jsonResponse = JSON.serialize(e.getMessage());
      							  return jsonResponse;
                                     }
                                     
                                     
                                     
                                 }
}