force-app/main/default/objects/phsSharedGoals__c/phsSharedGoals__c.object-meta.xml
<CustomObject>
    <label>phsSharedGoals</label>
    <nameField>
        <label>phsManagerGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsSharedGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsSharedGoals__c/fields/FocusAreaName__c.field-meta.xml
<CustomField>
    <fullName>FocusAreaName__c</fullName>
    <description>FocusAreaName for Manager Goal</description>
    <label>FocusAreaName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/fields/GoalName__c.field-meta.xml
<CustomField>
    <fullName>GoalName__c</fullName>
    <label>GoalName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/fields/GoalType__c.field-meta.xml
<CustomField>
    <fullName>GoalType__c</fullName>
    <description>Standard/custom goal</description>
    <label>GoalType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To hold status of goal</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Shared</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to contact</description>
    <label>UserId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>phsManagerGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsSharedGoalsStrategies__c/phsSharedGoalsStrategies__c.object-meta.xml
<CustomObject>
    <label>phsSharedGoalsStrategies</label>
    <nameField>
        <label>phsUserGoalsStrategies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsSharedGoalsStrategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsSharedGoalsStrategies__c/fields/phsSharedGoals__c.field-meta.xml
<CustomField>
    <fullName>phsSharedGoals__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>phsSharedGoals</label>
    <referenceTo>phsSharedGoals__c</referenceTo>
    <relationshipLabel>phsSharedGoalsStrategies</relationshipLabel>
    <relationshipName>phsSharedGoalsStrategies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsSharedGoalsStrategies__c/fields/StrategyDescription__c.field-meta.xml
<CustomField>
    <fullName>StrategyDescription__c</fullName>
    <label>StrategyDescription</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/phsSharedGoalsStrategies__c/fields/StrategyName__c.field-meta.xml
<CustomField>
    <fullName>StrategyName__c</fullName>
    <label>StrategyName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/phsUserGoalsStrategies__c.object-meta.xml
<CustomObject>
    <label>phsUserGoalsStrategies</label>
    <nameField>
        <label>phsUserGoalsStrategies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsUserGoalsStrategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/GoalId__c.field-meta.xml
<CustomField>
    <fullName>GoalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GoalId</label>
    <referenceTo>phsUserGoals__c</referenceTo>
    <relationshipLabel>phsUserGoalsStrategies</relationshipLabel>
    <relationshipName>phsUserGoalsStrategies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/StrategyDescription__c.field-meta.xml
<CustomField>
    <fullName>StrategyDescription__c</fullName>
    <label>StrategyDescription</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/StrategyType__c.field-meta.xml
<CustomField>
    <fullName>StrategyType__c</fullName>
    <label>StrategyType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/phsSharedGoalController.cls
public without sharing class phsSharedGoalController {
  
   
@AuraEnabled() 
    public static string getSharedGoalList() {
        phsUtilityController utility=new phsUtilityController();
       	String userId=utility.getContactId();
      	String reportToId=  utility.getReportId();
        List<CommonGoal> commongoals=new List<CommonGoal>();
        List<phsSharedGoals__c> goals = new List<phsSharedGoals__c>(); 
        try
        {
        goals = [SELECT Id , GoalName__c , GoalType__c  ,Status__c,UserId__c,FocusAreaName__c ,CreatedBy.FirstName,CreatedBy.LastName  FROM phsSharedGoals__c where UserId__c =: reportToId];
            
            for(phsSharedGoals__c g : goals)
            {
                CommonGoal c=new CommonGoal();
                c.goalId=g.Id;
                c.goalName=g.GoalName__c;
                c.goalType=g.GoalType__c;
                c.status=g.Status__c;
                c.focusAreaName=g.FocusAreaName__c;
                c.SharedBy=g.CreatedBy.FirstName +' '+g.CreatedBy.LastName;
                commongoals.add(c);
            }
            
                String jsonResponse = JSON.serialize(commongoals);
        return jsonResponse;
        }
        catch(Exception e)
        {
            System.debug('The following exception has occurred: ' + e.getMessage()); 
                 String jsonResponse = JSON.serialize(e.getMessage());
        return jsonResponse;
        }

    }
    
    class CommonGoal {
	public  String goalId ;
   	public  String goalName ; 
   	public  String goalType; 
    public  String focusAreaName ; 
    public  String status ; 
        public String SharedBy;
            
}

    
    
        @AuraEnabled() 
    	public static String addSharedGoal(String goalName,String focusArea) {
        try
        {
            phsUtilityController utility=new phsUtilityController();
       		String userId=new phsUtilityController().getContactId();
            phsSharedGoals__c obj=new phsSharedGoals__c();
            obj.GoalName__c=goalName;
           // obj.GoalType__c='Manager';
            obj.FocusAreaName__c=focusArea;
            obj.Status__c='Shared';
            obj.UserId__c=userId;
            insert obj;
            String jsonResponse = JSON.serialize(obj.Id);
        	return jsonResponse;
                                     
        }
        catch(Exception e)
        {
            System.debug('The following exception has occurred: ' + e.getMessage()); 
            String jsonResponse = JSON.serialize(e.getMessage());
        	return jsonResponse;
        }
        
    }
    
        class Strategy
{
    public String strategyId;
    public String strategyName;
    public String goalId;
    public integer rowNo=0;
    public string description;
    public boolean isShow=false;
}
      @AuraEnabled() 
    	public static String addSharedGoalStrategies(String data) {
         try
        {
        List<Strategy> strategyList = (List<Strategy>)JSON.deserialize(data, List<Strategy>.class);
            //(List<Strategy>)JSON.deserialize(data,Strategy.class);
            
        for(Strategy s : strategyList)
        {
            phsSharedGoalsStrategies__c c=new phsSharedGoalsStrategies__c();
            c.StrategyName__c=s.strategyName;
            c.phsSharedGoals__c=s.goalId;
            c.StrategyDescription__c=s.description;
            insert c;
        }
        String jsonResponse = JSON.serialize(true);
        return jsonResponse;
        }
        catch(Exception e)
        {
             System.debug('The following exception has occurred: ' + e.getMessage()); 
            String jsonResponse = JSON.serialize(e.getMessage());
        return jsonResponse;
        }
    }
    
     @AuraEnabled() 
     public static String getGoalStrategiesList(String userGoalId) {
        
      
        List<phsUserGoalsStrategies__c> phsStrategieslist = new List<phsUserGoalsStrategies__c>(); 
        List<Strategy> strategieslist = new List<Strategy>(); 
        try
        {
            integer counter=0;
        phsStrategieslist = [SELECT Id , Strategy__c, StrategyType__c ,GoalId__c ,StrategyDescription__c
                            FROM phsUserGoalsStrategies__c where GoalId__c =: userGoalId ];
             for (phsUserGoalsStrategies__c s: phsStrategieslist) {
        Strategy obj=new Strategy();
            obj.strategyId=s.Id;
            obj.strategyName=s.Strategy__c;
            obj.goalId=s.GoalId__c;
                 counter++;
                 obj.rowNo=counter;
                 obj.description=s.StrategyDescription__c;
                 obj.isShow=false;
                 
            strategieslist.add(obj);
             } 
		}
              catch(Exception e)
        {
            System.debug('The following exception has occurred: ' + e.getMessage()); 
        }
          String jsonResponse = JSON.serialize(strategieslist);
        return jsonResponse;
            
    }
    
   
    
        /*
    @AuraEnabled(cacheable=true) 
    public static boolean updateSharedGoal(String goalId, String status) {
        try
        {
          
                            phsManagerGoals__c a = [SELECT Id , Status__c   from phsManagerGoals__c WHERE Id  =: goalId LIMIT 1];
    									a.Status__c = status;
    									update a;
                                        return true; 
        }
        catch(Exception e)
        {
             System.debug('The following exception has occurred: ' + e.getMessage()); 
             return false;
        }
        
    }
    */
}