force-app/main/default/objects/phsFocusArea__c/phsFocusArea__c.object-meta.xml
<CustomObject>
    <label>phsFocusArea</label>
    <nameField>
        <label>phsFocusArea Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsFocusArea</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsFocusArea__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the Focus Area</description>
    <label>Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/phsGoals__c.object-meta.xml
<CustomObject>
    <label>phsGoals</label>
    <nameField>
        <label>phsGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsGoals__c/fields/FocusAreaId__c.field-meta.xml
<CustomField>
    <fullName>FocusAreaId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to Object FocusArea</description>
    <label>FocusAreaId</label>
    <referenceTo>phsFocusArea__c</referenceTo>
    <relationshipLabel>phsGoals</relationshipLabel>
    <relationshipName>phsGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the goal</description>
    <label>Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Individual/Manager</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/phsUserGoals__c.object-meta.xml
<CustomObject>
    <label>phsUserGoals</label>
    <nameField>
        <label>phsUserGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsUserGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsUserGoals__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True or false to check if goal is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/FocusArea__c.field-meta.xml
<CustomField>
    <fullName>FocusArea__c</fullName>
    <description>Name of the FocusArea</description>
    <label>FocusArea</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalAdherence__c.field-meta.xml
<CustomField>
    <fullName>GoalAdherence__c</fullName>
    <description>This field stores number for goal adherence value</description>
    <label>GoalAdherence</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalEffectiveness__c.field-meta.xml
<CustomField>
    <fullName>GoalEffectiveness__c</fullName>
    <description>This field stores number for goal effectiveness value</description>
    <label>GoalEffectiveness</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalName__c.field-meta.xml
<CustomField>
    <fullName>GoalName__c</fullName>
    <description>Name of the goal</description>
    <label>GoalName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalStrategyStatus__c.field-meta.xml
<CustomField>
    <fullName>GoalStrategyStatus__c</fullName>
    <label>GoalStrategyStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Established</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalType__c.field-meta.xml
<CustomField>
    <fullName>GoalType__c</fullName>
    <description>Standard goal / custom goal</description>
    <label>GoalType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Shared</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/StandardGoalId__c.field-meta.xml
<CustomField>
    <fullName>StandardGoalId__c</fullName>
    <label>StandardGoalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to contact</description>
    <label>UserId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>phsUserGoals</relationshipLabel>
    <relationshipName>phsUserGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/phsUserGoalsStrategies__c.object-meta.xml
<CustomObject>
    <label>phsUserGoalsStrategies</label>
    <nameField>
        <label>phsUserGoalsStrategies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsUserGoalsStrategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/GoalId__c.field-meta.xml
<CustomField>
    <fullName>GoalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GoalId</label>
    <referenceTo>phsUserGoals__c</referenceTo>
    <relationshipLabel>phsUserGoalsStrategies</relationshipLabel>
    <relationshipName>phsUserGoalsStrategies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/StrategyType__c.field-meta.xml
<CustomField>
    <fullName>StrategyType__c</fullName>
    <label>StrategyType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/phsUserGoalStrategyControllerTest.cls
@isTest
public class phsUserGoalStrategyControllerTest {
    
    private static Contact createContact() {
        Contact c = new Contact(
            LastName = 'Test Contact',
            Email = 'test' + System.currentTimeMillis() + '@example.com'
        );
        insert c;
        return c;
    }
    
    
    private static phsUserGoals__c createUserGoal() {
        phsFocusArea__c focusArea=new phsFocusArea__c(Name__c='Time Management',Name='Time Management');
        insert focusArea;
        phsGoals__c goal = new phsGoals__c(Name='Time Management',FocusAreaId__c=focusArea.Id,Name__c='Test Goal4',Role__c='Individual');
        insert goal;
        Contact c=phsUserGoalStrategyControllerTest.createContact();        
        phsUserGoals__c userGoal=new phsUserGoals__c(Active__c=true,FocusArea__c='Time Management',GoalAdherence__c=3.0,
                                                     GoalEffectiveness__c=3.0,GoalName__c='Time Management',GoalStrategyStatus__c='In Process',GoalType__c='Individual'
                                                     ,Name=goal.Id,UserId__c=c.Id,StandardGoalId__c=goal.Id );        
        return userGoal;
    }
    
    @IsTest static void testaddUserGoalStrategy() 
    {
        phsUserGoals__c userGoal=phsUserGoalStrategyControllerTest.createUserGoal();
        Test.startTest();
        phsUserGoalStrategyController.addUserGoalStrategy(userGoal.Id,  'Put Timer on every work to complete on time3','Standard');
        Test.stopTest();
        List<phsUserGoalsStrategies__c> strategies = [SELECT Name FROM phsUserGoalsStrategies__c where GoalId__c =  :userGoal.Id];
        System.assertEquals(1, strategies.size());
        
    }
    @IsTest static void testaddUserGoalStrategy_Negative() 
    {
        phsUserGoals__c userGoal=phsUserGoalStrategyControllerTest.createUserGoal();
        Test.startTest();
        phsUserGoalStrategyController.addUserGoalStrategy(userGoal.Id,  'Put Timer on every work to complete on time2','Wrong Data');
        Test.stopTest();
        List<phsUserGoalsStrategies__c> goals = [SELECT Name FROM phsUserGoalsStrategies__c where GoalId__c =  :userGoal.Id];
        System.assertEquals(0, goals.size());
        
    }
    
    @IsTest static void testgetUserGoalStrategies() 
    {
        phsUserGoals__c userGoal=phsUserGoalStrategyControllerTest.createUserGoal();        
        phsUserGoalsStrategies__c strategy=new phsUserGoalsStrategies__c(GoalId__c=userGoal.Id,Strategy__c='Put Timer on every work to complete on time1',StrategyType__c='Standard');
        insert strategy;        
        Test.startTest();
        String results= phsUserGoalStrategyController.getUserGoalStrategies(userGoal.Id);
        Test.stopTest();
        System.assert(results.contains('Put Timer on every work to complete on time'));
        
    }
    
    
}