force-app/main/default/objects/phsFocusArea__c/phsFocusArea__c.object-meta.xml
<CustomObject>
    <label>phsFocusArea</label>
    <nameField>
        <label>phsFocusArea Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsFocusArea</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsFocusArea__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the Focus Area</description>
    <label>Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/phsGoals__c.object-meta.xml
<CustomObject>
    <label>phsGoals</label>
    <nameField>
        <label>phsGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsGoals__c/fields/FocusAreaId__c.field-meta.xml
<CustomField>
    <fullName>FocusAreaId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to Object FocusArea</description>
    <label>FocusAreaId</label>
    <referenceTo>phsFocusArea__c</referenceTo>
    <relationshipLabel>phsGoals</relationshipLabel>
    <relationshipName>phsGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the goal</description>
    <label>Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Individual/Manager</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/phsUserGoals__c.object-meta.xml
<CustomObject>
    <label>phsUserGoals</label>
    <nameField>
        <label>phsUserGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsUserGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsUserGoals__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True or false to check if goal is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/FocusArea__c.field-meta.xml
<CustomField>
    <fullName>FocusArea__c</fullName>
    <description>Name of the FocusArea</description>
    <label>FocusArea</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalAdherence__c.field-meta.xml
<CustomField>
    <fullName>GoalAdherence__c</fullName>
    <description>This field stores number for goal adherence value</description>
    <label>GoalAdherence</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalEffectiveness__c.field-meta.xml
<CustomField>
    <fullName>GoalEffectiveness__c</fullName>
    <description>This field stores number for goal effectiveness value</description>
    <label>GoalEffectiveness</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalName__c.field-meta.xml
<CustomField>
    <fullName>GoalName__c</fullName>
    <description>Name of the goal</description>
    <label>GoalName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalStrategyStatus__c.field-meta.xml
<CustomField>
    <fullName>GoalStrategyStatus__c</fullName>
    <label>GoalStrategyStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Established</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalType__c.field-meta.xml
<CustomField>
    <fullName>GoalType__c</fullName>
    <description>Standard goal / custom goal</description>
    <label>GoalType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Shared</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/LastCheckInDate__c.field-meta.xml
<CustomField>
    <fullName>LastCheckInDate__c</fullName>
    <description>This hold date of last check-in by user</description>
    <label>LastCheckInDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/ManagerFeedback__c.field-meta.xml
<CustomField>
    <fullName>ManagerFeedback__c</fullName>
    <label>ManagerFeedback</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/SharedBy__c.field-meta.xml
<CustomField>
    <fullName>SharedBy__c</fullName>
    <label>SharedBy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/StandardGoalId__c.field-meta.xml
<CustomField>
    <fullName>StandardGoalId__c</fullName>
    <label>StandardGoalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to contact</description>
    <label>UserId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>phsUserGoals</relationshipLabel>
    <relationshipName>phsUserGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/phsUserGoalsStrategies__c.object-meta.xml
<CustomObject>
    <label>phsUserGoalsStrategies</label>
    <nameField>
        <label>phsUserGoalsStrategies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsUserGoalsStrategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/GoalId__c.field-meta.xml
<CustomField>
    <fullName>GoalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GoalId</label>
    <referenceTo>phsUserGoals__c</referenceTo>
    <relationshipLabel>phsUserGoalsStrategies</relationshipLabel>
    <relationshipName>phsUserGoalsStrategies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/StrategyType__c.field-meta.xml
<CustomField>
    <fullName>StrategyType__c</fullName>
    <label>StrategyType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/phsUserGoalsControllerTest.cls
@isTest
public class phsUserGoalsControllerTest {
    
    private static Contact createContact() {
        Survey__c s = new Survey__c(); 
        insert s;
        
        Contact c = new Contact(
            LastName = 'Test Contact',
            Email = 'test' + System.currentTimeMillis() + '@example.com',
            Most_Recent_Survey__c = s.Id
        );
        insert c;
        return c;
    }
    private static phsUserGoals__c createUserGoal() {
        phsFocusArea__c focusArea=new phsFocusArea__c(Name__c='Time Management',Name='Time Management');
        insert focusArea;
        phsGoals__c goal = new phsGoals__c(Name='Time Management',FocusAreaId__c=focusArea.Id,Name__c='Test Goal4',Role__c='Individual');
        insert goal;
        Contact c=phsUserGoalsControllerTest.createContact();
        Contact c1=phsUserGoalsControllerTest.createContact();   
        phsUserGoals__c userGoal=new phsUserGoals__c(Active__c=true,FocusArea__c='Time Management',GoalAdherence__c=3.0,
                                                     GoalEffectiveness__c=3.0,GoalName__c='Time Management',GoalStrategyStatus__c='In Progress',GoalType__c='Individual'
                                                     ,Name=goal.Id,UserId__c=c.Id,StandardGoalId__c=goal.Id,LastCheckInDate__c=Date.today(),
                                                     SharedBy__c=c1.Id,ManagerFeedback__c='Good' );
        insert userGoal;
        phsUserGoalsStrategies__c strategy=new phsUserGoalsStrategies__c(GoalId__c=userGoal.Id,Strategy__c='Put Timer on every work to complete on time1',
                                                                         StrategyType__c='Standard');
        insert strategy;
        return userGoal;
    }
    
    @IsTest static void testgetUserGoalList() 
    {
        phsUserGoals__c userGoal=phsUserGoalsControllerTest.createUserGoal();
        Test.startTest();
        String results=phsUserGoalsController.getUserGoalList();
        Test.stopTest();
        List<phsUserGoals__c> goals = [SELECT Id FROM phsUserGoals__c ];
        System.assertEquals(1, goals.size());    
    }
    
    @IsTest static void testgetMyUserGoalList() 
    {
        
        phsFocusArea__c focusArea=new phsFocusArea__c(Name__c='Time Management',Name='Time Management');
        insert focusArea;
        phsGoals__c goal = new phsGoals__c(Name='Time Management',FocusAreaId__c=focusArea.Id,Name__c='Test Goal4',Role__c='Individual');
        insert goal;
        Contact c=phsUserGoalsControllerTest.createContact();
        Contact c1=phsUserGoalsControllerTest.createContact();
        phsUserGoals__c userGoal=new phsUserGoals__c(Active__c=true,FocusArea__c='Time Management',GoalAdherence__c=3.0,
                                                     GoalEffectiveness__c=3.0,GoalName__c='Time Management',GoalStrategyStatus__c='In Progress',GoalType__c='Individual'
                                                     ,Name=goal.Id,UserId__c=c.Id,StandardGoalId__c=goal.Id,LastCheckInDate__c=Date.today(),
                                                     SharedBy__c=c1.Id,ManagerFeedback__c='Good' );
        insert userGoal;
        
        Test.startTest();
        String results=phsUserGoalsController.getMyUserGoalList(c.Id);
        Test.stopTest();
        List<phsUserGoals__c> goals = [SELECT Id FROM phsUserGoals__c ];
        System.assertEquals(1, goals.size());
        System.debug('Test : '+results);
        
    }
    
    @IsTest static void testupdateManagerFeedback() 
    {
        phsUserGoals__c userGoal=phsUserGoalsControllerTest.createUserGoal();        
        Test.startTest();
        String results=phsUserGoalsController.updateManagerFeedback(userGoal.Id,'New Feedback');
        Test.stopTest();
        List<phsUserGoals__c> goals = [SELECT Id, ManagerFeedback__c FROM phsUserGoals__c ];
        System.assertEquals('New Feedback', goals[0].ManagerFeedback__c);        
    }
    
    @IsTest static void testgetUserGoalListUpdate() 
    {
        phsUserGoals__c userGoal= createUserGoal();
        
        Test.startTest();
        String results=phsUserGoalsController.getUserGoalListUpdate();
        Test.stopTest();
        List<phsUserGoals__c> goals = [SELECT Id FROM phsUserGoals__c ];
        System.assertEquals(1, goals.size());
        System.debug('Test : '+results);
        
    }
    
    @IsTest static void testaddUserGoal() 
    {        
        phsFocusArea__c focusArea=new phsFocusArea__c(Name__c='Time Management',Name='Time Management');
        insert focusArea;
        phsGoals__c goal = new phsGoals__c(Name='Time Management',FocusAreaId__c=focusArea.Id,Name__c='Test Goal4',Role__c='Individual');
        insert goal;
        Contact c=phsUserGoalsControllerTest.createContact();
        Contact c1=phsUserGoalsControllerTest.createContact();
        
        Test.startTest();
        String results=phsUserGoalsController.addUserGoal('Time Management','Individual',  focusArea.Id,
                                                          null,goal.Id,null , null, 'true', 'Test Strategy');
        Test.stopTest();
        List<phsUserGoals__c> goalList=[Select Id from phsUserGoals__c];
        System.assertEquals(1, goalList.size());
        
    }
    
    
    @IsTest static void testaddUserGoalExists() 
    {
        
        phsFocusArea__c focusArea=new phsFocusArea__c(Name__c='Time Management',Name='Time Management');
        insert focusArea;
        phsGoals__c goal = new phsGoals__c(Name='Time Management',FocusAreaId__c=focusArea.Id,Name__c='Test Goal4',Role__c='Individual');
        insert goal;
        Contact c=phsUserGoalsControllerTest.createContact();
        Contact c1=phsUserGoalsControllerTest.createContact();
        phsUserGoals__c userGoal=new phsUserGoals__c(Active__c=true,FocusArea__c='Time Management',GoalAdherence__c=3.0,
                                                     GoalEffectiveness__c=3.0,GoalName__c='Time Management',GoalStrategyStatus__c='In Progress',GoalType__c='Individual'
                                                     ,Name=goal.Id,UserId__c=c.Id,StandardGoalId__c=goal.Id,LastCheckInDate__c=Date.today(),
                                                     SharedBy__c=c1.Id,ManagerFeedback__c='Good' );
        insert userGoal;
        phsUserGoalsStrategies__c strategy=new phsUserGoalsStrategies__c(GoalId__c=userGoal.Id,Strategy__c='Test Strategy',StrategyType__c='Standard');
        insert strategy;
        
        Test.startTest();
        String results=phsUserGoalsController.addUserGoal('Time Management','Individual',  focusArea.Id,
                                                          null,goal.Id,null , null, 'true', 'Test Strategy');
        Test.stopTest();
        List<phsUserGoals__c> goalList=[Select Id from phsUserGoals__c];
        System.assertEquals(1, goalList.size());
        
    }
    
    @IsTest static void testupdateUserGoal() 
    {
        phsUserGoals__c userGoal= createUserGoal();
        double d=5.0;
        Test.startTest();
        String results=phsUserGoalsController.updateUserGoal(userGoal.Id,d,d,true, 'Established' );
        Test.stopTest();
        List<phsUserGoals__c> goalList=[Select Id,GoalStrategyStatus__c from phsUserGoals__c];
        System.assertEquals('Established', goalList[0].GoalStrategyStatus__c);        
    }
    
}