force-app/main/default/objects/phsFocusArea__c/phsFocusArea__c.object-meta.xml
<CustomObject>
    <label>phsFocusArea</label>
    <nameField>
        <label>phsFocusArea Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsFocusArea</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsFocusArea__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the Focus Area</description>
    <label>Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/phsGoals__c.object-meta.xml
<CustomObject>
    <label>phsGoals</label>
    <nameField>
        <label>phsGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsGoals__c/fields/FocusAreaId__c.field-meta.xml
<CustomField>
    <fullName>FocusAreaId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to Object FocusArea</description>
    <label>FocusAreaId</label>
    <referenceTo>phsFocusArea__c</referenceTo>
    <relationshipLabel>phsGoals</relationshipLabel>
    <relationshipName>phsGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the goal</description>
    <label>Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Individual/Manager</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/phsGoalController.cls
public without sharing class phsGoalController {
    
    @AuraEnabled() 
    public static String getGoalList(String role ) {
   
        List<CommonGoal> allGoals=new  List<CommonGoal>();
        List<phsGoals__c> goals = new List<phsGoals__c>();         
        try
        {
            goals = [SELECT Id , Name, Name__c    ,FocusAreaId__r.Name__c, Role__c FROM phsGoals__c where Role__c =: role];
            for (phsGoals__c g: goals) {
                CommonGoal obj=new CommonGoal();
                obj.goalId=g.Id;
                obj.goalName=g.Name__c;
                obj.goalType='Standard';
                obj.focusAreaName=g.FocusAreaId__r.Name__c;
                allGoals.add(obj);
                
            }
            String jsonResponse = JSON.serialize(allGoals);
            return jsonResponse;
        }
        catch(Exception e){
            System.debug('The following exception has occurred: ' + e.getMessage()); 
            String jsonResponse = JSON.serialize(e.getMessage());
            return jsonResponse;
        }
        
    }
    class CommonGoal {
        public  String goalId ;
        public  String goalName ; 
        public  String goalType; 
        public  String focusAreaName ; 
    }
}