force-app/main/default/objects/phsFocusArea__c/phsFocusArea__c.object-meta.xml
<CustomObject>
    <label>phsFocusArea</label>
    <nameField>
        <label>phsFocusArea Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsFocusArea</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsFocusArea__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the Focus Area</description>
    <label>Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/phsGoals__c.object-meta.xml
<CustomObject>
    <label>phsGoals</label>
    <nameField>
        <label>phsGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsGoals__c/fields/FocusAreaId__c.field-meta.xml
<CustomField>
    <fullName>FocusAreaId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to Object FocusArea</description>
    <label>FocusAreaId</label>
    <referenceTo>phsFocusArea__c</referenceTo>
    <relationshipLabel>phsGoals</relationshipLabel>
    <relationshipName>phsGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the goal</description>
    <label>Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Individual/Manager</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/phsSharedGoals__c.object-meta.xml
<CustomObject>
    <label>phsSharedGoals</label>
    <nameField>
        <label>phsManagerGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsSharedGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsSharedGoals__c/fields/FocusAreaName__c.field-meta.xml
<CustomField>
    <fullName>FocusAreaName__c</fullName>
    <description>FocusAreaName for Manager Goal</description>
    <label>FocusAreaName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/fields/GoalName__c.field-meta.xml
<CustomField>
    <fullName>GoalName__c</fullName>
    <label>GoalName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/fields/GoalType__c.field-meta.xml
<CustomField>
    <fullName>GoalType__c</fullName>
    <description>Standard/custom goal</description>
    <label>GoalType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To hold status of goal</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Shared</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to contact</description>
    <label>UserId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>phsManagerGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsSharedGoalsStrategies__c/phsSharedGoalsStrategies__c.object-meta.xml
<CustomObject>
    <label>phsSharedGoalsStrategies</label>
    <nameField>
        <label>phsUserGoalsStrategies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsSharedGoalsStrategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsSharedGoalsStrategies__c/fields/phsSharedGoals__c.field-meta.xml
<CustomField>
    <fullName>phsSharedGoals__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>phsSharedGoals</label>
    <referenceTo>phsSharedGoals__c</referenceTo>
    <relationshipLabel>phsSharedGoalsStrategies</relationshipLabel>
    <relationshipName>phsSharedGoalsStrategies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsSharedGoalsStrategies__c/fields/StrategyDescription__c.field-meta.xml
<CustomField>
    <fullName>StrategyDescription__c</fullName>
    <label>StrategyDescription</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/phsSharedGoalsStrategies__c/fields/StrategyName__c.field-meta.xml
<CustomField>
    <fullName>StrategyName__c</fullName>
    <label>StrategyName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsStrategies__c/phsStrategies__c.object-meta.xml
<CustomObject>
    <label>phsStrategies</label>
    <nameField>
        <label>phsStrategies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsStrategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsStrategies__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the Strategy</description>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsStrategies__c/fields/phsGoals__c.field-meta.xml
<CustomField>
    <fullName>phsGoals__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to Object StandardGoals</description>
    <label>phsGoals</label>
    <referenceTo>phsGoals__c</referenceTo>
    <relationshipLabel>phsStrategies</relationshipLabel>
    <relationshipName>phsStrategies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/phsUserGoals__c.object-meta.xml
<CustomObject>
    <label>phsUserGoals</label>
    <nameField>
        <label>phsUserGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsUserGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsUserGoals__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True or false to check if goal is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/FocusArea__c.field-meta.xml
<CustomField>
    <fullName>FocusArea__c</fullName>
    <description>Name of the FocusArea</description>
    <label>FocusArea</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalAdherence__c.field-meta.xml
<CustomField>
    <fullName>GoalAdherence__c</fullName>
    <description>This field stores number for goal adherence value</description>
    <label>GoalAdherence</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalEffectiveness__c.field-meta.xml
<CustomField>
    <fullName>GoalEffectiveness__c</fullName>
    <description>This field stores number for goal effectiveness value</description>
    <label>GoalEffectiveness</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalName__c.field-meta.xml
<CustomField>
    <fullName>GoalName__c</fullName>
    <description>Name of the goal</description>
    <label>GoalName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalStrategyStatus__c.field-meta.xml
<CustomField>
    <fullName>GoalStrategyStatus__c</fullName>
    <label>GoalStrategyStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Established</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalType__c.field-meta.xml
<CustomField>
    <fullName>GoalType__c</fullName>
    <description>Standard goal / custom goal</description>
    <label>GoalType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Shared</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/StandardGoalId__c.field-meta.xml
<CustomField>
    <fullName>StandardGoalId__c</fullName>
    <label>StandardGoalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To hold status of goal</description>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to contact</description>
    <label>UserId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>phsUserGoals</relationshipLabel>
    <relationshipName>phsUserGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/phsUserGoalsStrategies__c.object-meta.xml
<CustomObject>
    <label>phsUserGoalsStrategies</label>
    <nameField>
        <label>phsUserGoalsStrategies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsUserGoalsStrategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/GoalId__c.field-meta.xml
<CustomField>
    <fullName>GoalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GoalId</label>
    <referenceTo>phsUserGoals__c</referenceTo>
    <relationshipLabel>phsUserGoalsStrategies</relationshipLabel>
    <relationshipName>phsUserGoalsStrategies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/StrategyDescription__c.field-meta.xml
<CustomField>
    <fullName>StrategyDescription__c</fullName>
    <label>StrategyDescription</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/StrategyType__c.field-meta.xml
<CustomField>
    <fullName>StrategyType__c</fullName>
    <label>StrategyType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/phsStrategyControllerTest.cls
@isTest
public class phsStrategyControllerTest {
    
    
    private static Contact createContact() {
        Contact c = new Contact(
            LastName = 'Test Contact',
            Email = 'test' + System.currentTimeMillis() + '@example.com'
        );
        insert c;
        return c;
    }
    
    private static phsUserGoals__c createUserGoalWithStrategy() {
        phsFocusArea__c focusArea=new phsFocusArea__c(Name__c='Time Management',Name='Time Management');
        insert focusArea;
        phsGoals__c goal = new phsGoals__c(Name='Time Management',FocusAreaId__c=focusArea.Id,Name__c='Test Goal4',Role__c='Individual');
        insert goal;
        Contact c=phsStrategyControllerTest.createContact();        
        phsUserGoals__c userGoal=new phsUserGoals__c(Active__c=true,FocusArea__c='Time Management',GoalAdherence__c=3.0,
                                                     GoalEffectiveness__c=3.0,GoalName__c='Time Management',GoalStrategyStatus__c='In Progress',GoalType__c='Individual'
                                                     ,Name=goal.Id,UserId__c=c.Id,StandardGoalId__c=goal.Id );
        insert userGoal;        
        phsUserGoalsStrategies__c strategy=new phsUserGoalsStrategies__c(GoalId__c=userGoal.Id,Name='My Unique Strategy',Strategy__c='My Unique Strategy',
                                                                         StrategyDescription__c='My Unique Strategy',StrategyType__c='Standard');
        insert strategy;
        return userGoal;       
    }
    
    
    private static phsGoals__c createGoalWithStrategy() 
    {
        phsFocusArea__c focusArea=new phsFocusArea__c(Name__c='Time Management',Name='Time Management');
        insert focusArea;
        phsGoals__c goal = new phsGoals__c(Name='Time Management',FocusAreaId__c=focusArea.Id,Name__c='Test Goal4',Role__c='Individual');
        insert goal;
        Contact c=phsStrategyControllerTest.createContact();
        phsStrategies__c strategy=new phsStrategies__c(phsGoals__c=goal.Id,Name__c='My Unique Strategy',Name='My Unique Strategy',
                                                       StrategyDescription__c='My Unique Strategy');
        insert strategy;
        return goal;        
    }
    
    
    @IsTest static void testgetStrategiesList() 
    {
        phsGoals__c goal=phsStrategyControllerTest.createGoalWithStrategy();
        Test.startTest();
        String results=   phsStrategyController.getStrategiesList(goal.Id);
        Test.stopTest();
        List<phsStrategies__c> strategies = [SELECT Id FROM phsStrategies__c where phsGoals__c = :goal.Id];
        System.assertEquals(1, strategies.size());  
    }
    
    private static phsUserGoals__c createUserGoalWithoutStrategy()
    {
        phsFocusArea__c focusArea=new phsFocusArea__c(Name__c='Time Management1',Name='Time Management1');
        insert focusArea;
        phsGoals__c goal = new phsGoals__c(Name='Time Management1',FocusAreaId__c=focusArea.Id,Name__c='Test Goal41',Role__c='Individual');
        insert goal;
        Contact c=phsStrategyControllerTest.createContact();
        
        phsUserGoals__c userGoal=new phsUserGoals__c(Active__c=true,FocusArea__c='Time Management1',GoalAdherence__c=3.0,
                                                     GoalEffectiveness__c=3.0,GoalName__c='Time Management1',GoalStrategyStatus__c='In Progress',GoalType__c='Individual'
                                                     ,Name=goal.Id,UserId__c=c.Id,StandardGoalId__c=goal.Id );
        insert userGoal;
        return userGoal;
    }
    @IsTest static void testaddStrategies() 
    {
        
        phsUserGoals__c userGoal= createUserGoalWithoutStrategy();
        String data ='[{"strategyName":"Test Strategy","goalId":"'+userGoal.Id+'","description":"Test Strategy"}]';
        
        Test.startTest();
        String results=   phsStrategyController.addStrategies(data);
        Test.stopTest();
        List<phsUserGoalsStrategies__c> strategies = [SELECT Id FROM phsUserGoalsStrategies__c where GoalId__c = :userGoal.Id];
        System.assert( strategies.size()>0);
        System.assert(results.contains('true'));
        
    }
    
    @IsTest static void testaddStrategy() 
    {
        phsUserGoals__c userGoal= createUserGoalWithoutStrategy();
        
        Test.startTest();
        String results=   phsStrategyController.addStrategy('Test Strategy1',userGoal.Id,'Test Strategy1');
        Test.stopTest();
        List<phsUserGoalsStrategies__c> strategies = [SELECT Id FROM phsUserGoalsStrategies__c where GoalId__c = :userGoal.Id];
        System.assert( strategies.size()>0);
        
        
    }
    
    
    @IsTest static void testaddStrategy_negative() 
    {
        phsUserGoals__c userGoal= createUserGoalWithoutStrategy();
        String results=   phsStrategyController.addStrategy('Test Strategy1',userGoal.Id,'Test Strategy1');        
        Test.startTest();
        results=phsStrategyController.addStrategy('Test Strategy1',userGoal.Id,'Test Strategy1');
        Test.stopTest();
        List<phsUserGoalsStrategies__c> strategies = [SELECT Id FROM phsUserGoalsStrategies__c where GoalId__c = :userGoal.Id];
        System.assert( strategies.size()==1);
        // System.assert( results.contains('Exists'));                
    }
    
    @IsTest static void testdeleteStrategy() 
    {
        phsUserGoals__c userGoal= createUserGoalWithoutStrategy();
        phsUserGoalsStrategies__c strategy=new phsUserGoalsStrategies__c(GoalId__c=userGoal.Id,Name='My Unique Strategy',Strategy__c='My Unique Strategy',
                                                                         StrategyDescription__c='My Unique Strategy',StrategyType__c='Standard');
        insert strategy;
        Test.startTest();
        
        String  results=phsStrategyController.deleteStrategy(strategy.Id);
        Test.stopTest();
        List<phsUserGoalsStrategies__c> strategies = [SELECT Id FROM phsUserGoalsStrategies__c];
        System.assertEquals(0, strategies.size());
        
        
    }
    
    @IsTest static void testgetUserGoalStrategiesList() 
    {
        phsUserGoals__c userGoal= createUserGoalWithoutStrategy();
        phsUserGoalsStrategies__c strategy=new phsUserGoalsStrategies__c(GoalId__c=userGoal.Id,Name='My Unique Strategy',Strategy__c='My Unique Strategy',
                                                                         StrategyDescription__c='My Unique Strategy',StrategyType__c='Standard');
        insert strategy;
        Test.startTest();
        
        String  results=phsStrategyController.getUserGoalStrategiesList(userGoal.Id);
        Test.stopTest();
        List<phsUserGoalsStrategies__c> strategies = [SELECT Id FROM phsUserGoalsStrategies__c where GoalId__c =: userGoal.Id];
        System.assert(strategies.size()>0);
        
        
    }
    
    @IsTest static void testgetSharedGoalStrategiesList() 
    {
        phsFocusArea__c focusArea=new phsFocusArea__c(Name__c='Time Management2',Name='Time Management2');
        insert focusArea;
        Contact c=phsStrategyControllerTest.createContact();
        phsSharedGoals__c goal = new phsSharedGoals__c(GoalName__c='Time Management2', GoalType__c='Standard', FocusAreaName__c=focusArea.Id,
                                                       Name='Test Goal42',Status__c='Active',UserId__c=c.Id);
        insert goal;
        
        phsSharedGoalsStrategies__c strategy=new phsSharedGoalsStrategies__c(phsSharedGoals__c=goal.Id,Name='My Unique Strategy',StrategyDescription__c='My Unique Strategy',
                                                                             StrategyName__c='My Unique Strategy');
        insert strategy;
        Test.startTest();
        
        String  results=phsStrategyController.getSharedGoalStrategiesList(goal.Id);
        Test.stopTest();
        List<phsSharedGoalsStrategies__c> strategies = [SELECT Id FROM phsSharedGoalsStrategies__c where phsSharedGoals__c =: goal.Id];
        System.assert(strategies.size()>0);        
        
    }
    
}