force-app/main/default/objects/phsFocusArea__c/phsFocusArea__c.object-meta.xml
<CustomObject>
    <label>phsFocusArea</label>
    <nameField>
        <label>phsFocusArea Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsFocusArea</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsFocusArea__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the Focus Area</description>
    <label>Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/phsGoals__c.object-meta.xml
<CustomObject>
    <label>phsGoals</label>
    <nameField>
        <label>phsGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsGoals__c/fields/FocusAreaId__c.field-meta.xml
<CustomField>
    <fullName>FocusAreaId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to Object FocusArea</description>
    <label>FocusAreaId</label>
    <referenceTo>phsFocusArea__c</referenceTo>
    <relationshipLabel>phsGoals</relationshipLabel>
    <relationshipName>phsGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the goal</description>
    <label>Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Individual/Manager</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/phsGoalControllerTest.cls
@isTest
public class phsGoalControllerTest {
    
    @IsTest static void testgetGoalList() 
    {
        phsFocusArea__c focusArea=new phsFocusArea__c(Name__c='Time Management',Name='Time Management');
        insert focusArea;
        phsGoals__c goal=new phsGoals__c(Name__c='Test Goal',FocusAreaId__c=focusArea.Id,Name='Test Goal',Role__c='Individual');
        insert goal;
        Test.startTest();
        String results= phsGoalController.getGoalList('Individual');
        Test.stopTest();
        System.assert(results.contains('Test Goal'));
        
    }

}