force-app/main/default/objects/phsFocusArea__c/phsFocusArea__c.object-meta.xml
<CustomObject>
    <label>phsFocusArea</label>
    <nameField>
        <label>phsFocusArea Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsFocusArea</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsFocusArea__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the Focus Area</description>
    <label>Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/phsGoals__c.object-meta.xml
<CustomObject>
    <label>phsGoals</label>
    <nameField>
        <label>phsGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsGoals__c/fields/FocusAreaId__c.field-meta.xml
<CustomField>
    <fullName>FocusAreaId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to Object FocusArea</description>
    <label>FocusAreaId</label>
    <referenceTo>phsFocusArea__c</referenceTo>
    <relationshipLabel>phsGoals</relationshipLabel>
    <relationshipName>phsGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the goal</description>
    <label>Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsGoals__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Individual/Manager</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/phsSharedGoals__c.object-meta.xml
<CustomObject>
    <label>phsSharedGoals</label>
    <nameField>
        <label>phsManagerGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsSharedGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsSharedGoals__c/fields/FocusAreaName__c.field-meta.xml
<CustomField>
    <fullName>FocusAreaName__c</fullName>
    <description>FocusAreaName for Manager Goal</description>
    <label>FocusAreaName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/fields/GoalName__c.field-meta.xml
<CustomField>
    <fullName>GoalName__c</fullName>
    <label>GoalName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/fields/GoalType__c.field-meta.xml
<CustomField>
    <fullName>GoalType__c</fullName>
    <description>Standard/custom goal</description>
    <label>GoalType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To hold status of goal</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Shared</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to contact</description>
    <label>UserId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>phsManagerGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsSharedGoalsStrategies__c/phsSharedGoalsStrategies__c.object-meta.xml
<CustomObject>
    <label>phsSharedGoalsStrategies</label>
    <nameField>
        <label>phsUserGoalsStrategies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsSharedGoalsStrategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsSharedGoalsStrategies__c/fields/phsSharedGoals__c.field-meta.xml
<CustomField>
    <fullName>phsSharedGoals__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>phsSharedGoals</label>
    <referenceTo>phsSharedGoals__c</referenceTo>
    <relationshipLabel>phsSharedGoalsStrategies</relationshipLabel>
    <relationshipName>phsSharedGoalsStrategies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsSharedGoalsStrategies__c/fields/StrategyDescription__c.field-meta.xml
<CustomField>
    <fullName>StrategyDescription__c</fullName>
    <label>StrategyDescription</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/phsSharedGoalsStrategies__c/fields/StrategyName__c.field-meta.xml
<CustomField>
    <fullName>StrategyName__c</fullName>
    <label>StrategyName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/phsUserGoals__c.object-meta.xml
<CustomObject>
    <label>phsUserGoals</label>
    <nameField>
        <label>phsUserGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsUserGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsUserGoals__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True or false to check if goal is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/FocusArea__c.field-meta.xml
<CustomField>
    <fullName>FocusArea__c</fullName>
    <description>Name of the FocusArea</description>
    <label>FocusArea</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalAdherence__c.field-meta.xml
<CustomField>
    <fullName>GoalAdherence__c</fullName>
    <description>This field stores number for goal adherence value</description>
    <label>GoalAdherence</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalEffectiveness__c.field-meta.xml
<CustomField>
    <fullName>GoalEffectiveness__c</fullName>
    <description>This field stores number for goal effectiveness value</description>
    <label>GoalEffectiveness</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalName__c.field-meta.xml
<CustomField>
    <fullName>GoalName__c</fullName>
    <description>Name of the goal</description>
    <label>GoalName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalStrategyStatus__c.field-meta.xml
<CustomField>
    <fullName>GoalStrategyStatus__c</fullName>
    <label>GoalStrategyStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Established</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalType__c.field-meta.xml
<CustomField>
    <fullName>GoalType__c</fullName>
    <description>Standard goal / custom goal</description>
    <label>GoalType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Shared</fullName>
            </value>
            <value>
                <fullName>Organization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/StandardGoalId__c.field-meta.xml
<CustomField>
    <fullName>StandardGoalId__c</fullName>
    <label>StandardGoalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To hold status of goal</description>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to contact</description>
    <label>UserId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>phsUserGoals</relationshipLabel>
    <relationshipName>phsUserGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/phsUserGoalsStrategies__c.object-meta.xml
<CustomObject>
    <label>phsUserGoalsStrategies</label>
    <nameField>
        <label>phsUserGoalsStrategies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsUserGoalsStrategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/GoalId__c.field-meta.xml
<CustomField>
    <fullName>GoalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GoalId</label>
    <referenceTo>phsUserGoals__c</referenceTo>
    <relationshipLabel>phsUserGoalsStrategies</relationshipLabel>
    <relationshipName>phsUserGoalsStrategies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/StrategyDescription__c.field-meta.xml
<CustomField>
    <fullName>StrategyDescription__c</fullName>
    <label>StrategyDescription</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/StrategyType__c.field-meta.xml
<CustomField>
    <fullName>StrategyType__c</fullName>
    <label>StrategyType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/phsSharedGoalControllerTest.cls
@isTest
public class phsSharedGoalControllerTest {
  private static Contact createContact() {
        Contact c = new Contact(
            LastName = 'Test Contact',
            Email = 'test' + System.currentTimeMillis() + '@example.com'
        );
        insert c;
        return c;
    }
    //Noyt working
      @IsTest static void testgetSharedGoalList() 
          {
             phsFocusArea__c focusArea=new phsFocusArea__c(Name__c='Time Management2',Name='Time Management2');
         insert focusArea;
                Contact c=phsSharedGoalControllerTest.createContact();
                Contact c2=phsSharedGoalControllerTest.createContact();
              
              c.ReportsToId=c2.Id;
         update c;
             
        phsSharedGoals__c goal = new phsSharedGoals__c(GoalName__c='Time Management2', GoalType__c='Standard', FocusAreaName__c=focusArea.Id,
                                                       Name='Test Goal42',Status__c='Active',UserId__c=c2.Id);
        insert goal;
        
    
         phsSharedGoalsStrategies__c strategy=new phsSharedGoalsStrategies__c(phsSharedGoals__c=goal.Id,Name='My Unique Strategy',StrategyDescription__c='My Unique Strategy',
                                                                          StrategyName__c='My Unique Strategy');
            insert strategy;
              Test.startTest();
           	 System.debug('Testxyz : '+ goal.Id); 
            String  results=phsSharedGoalController.getSharedGoalList();
              System.debug('Testxyz1 : '+ results); 
              Test.stopTest();
               List<phsSharedGoals__c> sharedGaols = [SELECT Id FROM phsSharedGoals__c ];
        	    System.assert(sharedGaols.size()>0);
              System.debug('Testxyz : '+ results); 
            
          }
    
        @IsTest static void testaddSharedGoal() 
          {
               Test.startTest();
           
            String  results=phsSharedGoalController.addSharedGoal('Test Shared Goal','Time Management');
               Test.stopTest();
               List<phsSharedGoals__c> sharedGoals = [SELECT Id FROM phsSharedGoals__c ];
        	    System.assert(sharedGoals.size()>0);
              //System.debug('Testxyz : '+ strategies.size()); 
              // System.assert( results.contains('Exists'));
          }
    
     @IsTest static void testaddSharedGoalStrategies_negative() 
          {
                phsFocusArea__c focusArea=new phsFocusArea__c(Name__c='Time Management2',Name='Time Management2');
         insert focusArea;
                Contact c=phsSharedGoalControllerTest.createContact();
           
        phsSharedGoals__c goal = new phsSharedGoals__c(GoalName__c='Time Management2', GoalType__c='Standard', FocusAreaName__c=focusArea.Id,
                                                       Name='Test Goal42',Status__c='Active',UserId__c=c.Id);
        insert goal;
        
              String data='{"strategyName":"Test Strategy","goalId":"'+goal.Id+'","description":"Test Strategy"}';
               Test.startTest();
           
            String  results=phsSharedGoalController.addSharedGoalStrategies(data);
               Test.stopTest();
               List<phsSharedGoalsStrategies__c> sharedGoalStrategy = [SELECT Id FROM phsSharedGoalsStrategies__c ];
        	   // System.assert(sharedGoalStrategy.size()>0);
              System.debug('Testxyz : '+ results); 
               System.assert( results.contains('Malformed JSON: Expected'));
          }
    
    
      @IsTest static void testaddSharedGoalStrategies() 
          {
                phsFocusArea__c focusArea=new phsFocusArea__c(Name__c='Time Management2',Name='Time Management2');
         insert focusArea;
                Contact c=phsSharedGoalControllerTest.createContact();
           
        phsSharedGoals__c goal = new phsSharedGoals__c(GoalName__c='Time Management2', GoalType__c='Standard', FocusAreaName__c=focusArea.Id,
                                                       Name='Test Goal42',Status__c='Active',UserId__c=c.Id);
        insert goal;
        
              String data='[{"strategyName":"Test Strategy","goalId":"'+goal.Id+'","description":"Test Strategy"}]';
               Test.startTest();
           
            String  results=phsSharedGoalController.addSharedGoalStrategies(data);
               Test.stopTest();
               List<phsSharedGoalsStrategies__c> sharedGoalStrategy = [SELECT Id FROM phsSharedGoalsStrategies__c ];
        	    System.assert(sharedGoalStrategy.size()>0);
              System.debug('Testxyz : '+ results); 
               //System.assert( results.contains('Malformed JSON: Expected'));
          }
    
    
    
    @IsTest static void testgetGoalStrategiesList() 
          {
              phsFocusArea__c focusArea=new phsFocusArea__c(Name__c='Time Management2',Name='Time Management2');
         insert focusArea;
        phsGoals__c goal = new phsGoals__c(Name='Time Management2',FocusAreaId__c=focusArea.Id,Name__c='Test Goal42',Role__c='Individual');
        insert goal;
          Contact c=phsSharedGoalControllerTest.createContact();
             
         phsUserGoals__c userGoal=new phsUserGoals__c(Active__c=true,FocusArea__c='Time Management2',GoalAdherence__c=3.0,
                                                      GoalEffectiveness__c=3.0,GoalName__c='Time Management2',GoalStrategyStatus__c='In Progress',GoalType__c='Individual'
                                                      ,Name=goal.Id,UserId__c=c.Id,StandardGoalId__c=goal.Id );
         insert userGoal;
         phsUserGoalsStrategies__c strategy=new phsUserGoalsStrategies__c(GoalId__c=userGoal.Id,Name='My Unique Strategy',Strategy__c='My Unique Strategy',
                                                                          StrategyDescription__c='My Unique Strategy',StrategyType__c='Standard');
            insert strategy;
              Test.startTest();
           	
            String  results=phsSharedGoalController.getGoalStrategiesList(userGoal.Id);
              Test.stopTest();
               List<phsUserGoalsStrategies__c> strategies = [SELECT Id FROM phsUserGoalsStrategies__c where GoalId__c =: userGoal.Id];
        	    System.assert(strategies.size()>0);
              System.debug('Testxyz : '+ results); 
              // System.assert( results.contains('Exists'));
              		
              
          }
    
    
    
    
}