force-app/main/default/objects/phsGoals__c/phsGoals__c.object-meta.xml
<CustomObject>
    <label>phsGoals</label>
    <nameField>
        <label>phsGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsGoals__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the goal</description>
    <label>Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/phsSharedGoals__c.object-meta.xml
<CustomObject>
    <label>phsSharedGoals</label>
    <nameField>
        <label>phsManagerGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsSharedGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsSharedGoals__c/fields/GoalName__c.field-meta.xml
<CustomField>
    <fullName>GoalName__c</fullName>
    <label>GoalName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsSharedGoals__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to contact</description>
    <label>UserId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>phsManagerGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsSharedGoalsStrategies__c/phsSharedGoalsStrategies__c.object-meta.xml
<CustomObject>
    <label>phsSharedGoalsStrategies</label>
    <nameField>
        <label>phsUserGoalsStrategies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsSharedGoalsStrategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsSharedGoalsStrategies__c/fields/phsSharedGoals__c.field-meta.xml
<CustomField>
    <fullName>phsSharedGoals__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>phsSharedGoals</label>
    <referenceTo>phsSharedGoals__c</referenceTo>
    <relationshipLabel>phsSharedGoalsStrategies</relationshipLabel>
    <relationshipName>phsSharedGoalsStrategies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsSharedGoalsStrategies__c/fields/StrategyDescription__c.field-meta.xml
<CustomField>
    <fullName>StrategyDescription__c</fullName>
    <label>StrategyDescription</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/phsSharedGoalsStrategies__c/fields/StrategyName__c.field-meta.xml
<CustomField>
    <fullName>StrategyName__c</fullName>
    <label>StrategyName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsStrategies__c/phsStrategies__c.object-meta.xml
<CustomObject>
    <label>phsStrategies</label>
    <nameField>
        <label>phsStrategies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsStrategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsStrategies__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Name of the Strategy</description>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsStrategies__c/fields/phsGoals__c.field-meta.xml
<CustomField>
    <fullName>phsGoals__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to Object StandardGoals</description>
    <label>phsGoals</label>
    <referenceTo>phsGoals__c</referenceTo>
    <relationshipLabel>phsStrategies</relationshipLabel>
    <relationshipName>phsStrategies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/phsUserGoals__c.object-meta.xml
<CustomObject>
    <label>phsUserGoals</label>
    <nameField>
        <label>phsUserGoals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsUserGoals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsUserGoals__c/fields/GoalName__c.field-meta.xml
<CustomField>
    <fullName>GoalName__c</fullName>
    <description>Name of the goal</description>
    <label>GoalName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/GoalStrategyStatus__c.field-meta.xml
<CustomField>
    <fullName>GoalStrategyStatus__c</fullName>
    <label>GoalStrategyStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Established</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/phsUserGoals__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Foreign key to contact</description>
    <label>UserId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>phsUserGoals</relationshipLabel>
    <relationshipName>phsUserGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/phsUserGoalsStrategies__c.object-meta.xml
<CustomObject>
    <label>phsUserGoalsStrategies</label>
    <nameField>
        <label>phsUserGoalsStrategies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>phsUserGoalsStrategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/GoalId__c.field-meta.xml
<CustomField>
    <fullName>GoalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GoalId</label>
    <referenceTo>phsUserGoals__c</referenceTo>
    <relationshipLabel>phsUserGoalsStrategies</relationshipLabel>
    <relationshipName>phsUserGoalsStrategies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/StrategyDescription__c.field-meta.xml
<CustomField>
    <fullName>StrategyDescription__c</fullName>
    <label>StrategyDescription</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/phsUserGoalsStrategies__c/fields/StrategyType__c.field-meta.xml
<CustomField>
    <fullName>StrategyType__c</fullName>
    <label>StrategyType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/phsStrategyController.cls
public without sharing class phsStrategyController {
    
   
 @AuraEnabled(cacheable=true) 
    public static String getStrategiesList(String goalId) {
        
      
        List<phsStrategies__c> phsStrategieslist = new List<phsStrategies__c>(); 
        List<Strategy> strategieslist = new List<Strategy>(); 
        try
        {
        phsStrategieslist = [SELECT Id , Name__c ,phsGoals__c , StrategyDescription__c
                            FROM phsStrategies__c where phsGoals__c =: goalId ];
             for (phsStrategies__c s: phsStrategieslist) {
        Strategy obj=new Strategy();
            obj.strategyId=s.Id;
            obj.strategyName=s.Name__c;
            obj.goalId=s.phsGoals__c;
             obj.description    =s.StrategyDescription__c;
                 
            strategieslist.add(obj);
             } 
		}
              catch(Exception e)
        {
            System.debug('The following exception has occurred: ' + e.getMessage()); 
        }
          String jsonResponse = JSON.serialize(strategieslist);
        return jsonResponse;
            
    }
    class Strategy
{
    public String strategyId;
    public String strategyName;
    public String goalId;
    public integer rowNo=0;
    public string description;
    public boolean isShow=false;
    public boolean isSelected=false;
}
    
    @AuraEnabled() 
    public static String addStrategies(String data) {
        try
        {
        List<Strategy> strategyList = (List<Strategy>)JSON.deserialize(data, List<Strategy>.class);
            //(List<Strategy>)JSON.deserialize(data,Strategy.class);
            
        for(Strategy s : strategyList)
        {
            phsUserGoalsStrategies__c c=new phsUserGoalsStrategies__c();
            c.Strategy__c=s.strategyName;
            c.GoalId__c=s.goalId;
            c.StrategyDescription__c=s.description;
            insert c;
        }
        String jsonResponse = JSON.serialize(true);
        return jsonResponse;
        }
        catch(Exception e)
        {
             System.debug('The following exception has occurred: ' + e.getMessage()); 
            String jsonResponse = JSON.serialize(e.getMessage());
        return jsonResponse;
        }
    }
    
    
        @AuraEnabled() 
    public static String addStrategy(String strategyName,String goalId,String description) {
        try
        {
       
            List<phsUserGoals__c> userGoal=new List<phsUserGoals__c>();
            
            userGoal=[Select Id, GoalName__c,UserId__c from phsUserGoals__c where Id=:goalId];
            
            String goalName=userGoal[0].GoalName__c;
            String userId=userGoal[0].UserId__c;
            
            List<phsUserGoalsStrategies__c> goalStrategyCheck=new List<phsUserGoalsStrategies__c>();
            goalStrategyCheck= [Select Id , Strategy__c , GoalId__r.UserId__c , GoalId__r.GoalName__c ,GoalId__r.Id,GoalId__r.GoalStrategyStatus__c  from phsUserGoalsStrategies__c 
                                      where GoalId__r.UserId__c =: userId and Strategy__c=: strategyName and GoalId__r.GoalName__c =: goalName];
            
            if(goalStrategyCheck.size()==0)
            {
            phsUserGoalsStrategies__c c=new phsUserGoalsStrategies__c();
            c.Strategy__c=strategyName;
            c.GoalId__c=goalId;
            c.StrategyDescription__c=description;
            insert c;
        
                addStrategyStatus objres=new addStrategyStatus();
                objres.status='true';
        String jsonResponse = JSON.serialize(objres);
        return jsonResponse;
            }
            else
            {
                 addStrategyStatus objres=new addStrategyStatus();
                objres.status='exists';
                objres.goalStatus=goalStrategyCheck[0].GoalId__r.GoalStrategyStatus__c;
                
         String jsonResponse = JSON.serialize(objres);
        return jsonResponse; 
            }
        }
        catch(Exception e)
        {
             System.debug('The following exception has occurred: ' + e.getMessage()); 
             addStrategyStatus objres=new addStrategyStatus();
                objres.status='false';
                objres.errorDetails= e.getMessage();
            String jsonResponse = JSON.serialize(objres);
        return jsonResponse;
        }
    }
    
    class addStrategyStatus
    {
        string status;
        string goalStatus;
        string errorDetails;
    }
    
    @AuraEnabled() 
    public static String deleteStrategy(String userGoalId) {
        try
        {
             List<phsUserGoalsStrategies__c> phsStrategieslist = new List<phsUserGoalsStrategies__c>(); 
        phsStrategieslist = [SELECT Id 
                            FROM phsUserGoalsStrategies__c where Id =: userGoalId ];
            delete phsStrategieslist;

        String jsonResponse = JSON.serialize(true);
        return jsonResponse;
        }
        catch(Exception e)
        {
             System.debug('The following exception has occurred: ' + e.getMessage()); 
            String jsonResponse = JSON.serialize(e.getMessage());
        return jsonResponse;
        }
       
    }
    
    
    
     @AuraEnabled() 
     public static String getUserGoalStrategiesList(String userGoalId) {
        
      
        List<phsUserGoalsStrategies__c> phsStrategieslist = new List<phsUserGoalsStrategies__c>(); 
        List<Strategy> strategieslist = new List<Strategy>(); 
        try
        {
            integer counter=0;
        phsStrategieslist = [SELECT Id , Strategy__c, StrategyType__c ,GoalId__c ,StrategyDescription__c
                            FROM phsUserGoalsStrategies__c where GoalId__c =: userGoalId ];
             for (phsUserGoalsStrategies__c s: phsStrategieslist) {
        Strategy obj=new Strategy();
            obj.strategyId=s.Id;
            obj.strategyName=s.Strategy__c;
            obj.goalId=s.GoalId__c;
                 counter++;
                 obj.rowNo=counter;
                 obj.description=s.StrategyDescription__c;
                 obj.isShow=false;
                 
            strategieslist.add(obj);
             } 
		}
              catch(Exception e)
        {
            System.debug('The following exception has occurred: ' + e.getMessage()); 
        }
          String jsonResponse = JSON.serialize(strategieslist);
        return jsonResponse;
            
    }
    
    
          @AuraEnabled(cacheable=true) 
    public static String getSharedGoalStrategiesList(String goalId) {
        
      
        List<phsSharedGoalsStrategies__c> phsStrategieslist = new List<phsSharedGoalsStrategies__c>(); 
        List<Strategy> strategieslist = new List<Strategy>(); 
        try
        {
        phsStrategieslist = [SELECT Id , StrategyName__c ,phsSharedGoals__c , StrategyDescription__c
                            FROM phsSharedGoalsStrategies__c where phsSharedGoals__c =: goalId ];
             for (phsSharedGoalsStrategies__c s: phsStrategieslist) {
        Strategy obj=new Strategy();
            obj.strategyId=s.Id;
            obj.strategyName=s.StrategyName__c;
            obj.goalId=s.phsSharedGoals__c;
             obj.description    =s.StrategyDescription__c;
                 
            strategieslist.add(obj);
             } 
		}
              catch(Exception e)
        {
            System.debug('The following exception has occurred: ' + e.getMessage()); 
        }
          String jsonResponse = JSON.serialize(strategieslist);
        return jsonResponse;
            
    }
}